/*
 * zkn_plonk.h — BLS12-381 PLONK proof verification (snarkjs compatible)
 *
 * Verifies PLONK proofs generated by snarkjs/circom over BLS12-381.
 *
 * Protocol follows Gabizon-Williamson-Ciobotaru (GWC19) with
 * Fiat-Shamir via Keccak-256 matching snarkjs plonk_verify.js.
 *
 * Pairing equation (2 pairings, batched):
 *   e(A1, [x]₂) · e(-A2, G₂) == 1
 *
 * where:
 *   A1 = [Wξ] + u·[Wξω]
 *   A2 = ξ·[Wξ] + uξω·[Wξω] + [F] - [E]
 *
 * Copyright (c) 2025 ZKNOX / Kohaku
 */

#ifndef ZKN_PLONK_H
#define ZKN_PLONK_H

#include "zkn_mont384.h"
#include "zkn_g1_384.h"
#include "zkn_g2_384.h"
#include "zkn_fp12_384.h"

#ifdef __cplusplus
extern "C" {
#endif

/* ── Sizes ────────────────────────────────────────────────────────────── */

#define ZKN_PLONK_FR_BYTES    32    /* BLS12-381 scalar field: 255 bits    */
#define ZKN_PLONK_FP_BYTES    48    /* BLS12-381 base field:   381 bits    */
#define ZKN_PLONK_G1_BYTES    96    /* uncompressed affine G1: 2 × 48     */
#define ZKN_PLONK_G2_BYTES   192    /* uncompressed affine G2: 4 × 48     */
#define ZKN_PLONK_MAX_PUB     16    /* max public inputs                   */

/* ── Verification Key ─────────────────────────────────────────────────── */

typedef struct {
    int      power;                    /* n = 2^power                      */
    int      n_public;                 /* number of public inputs           */

    /* Coset generators k1, k2 ∈ Fr (big-endian 32 bytes) */
    uint8_t  k1[ZKN_PLONK_FR_BYTES];
    uint8_t  k2[ZKN_PLONK_FR_BYTES];

    /* Primitive n-th root of unity ω ∈ Fr */
    uint8_t  w[ZKN_PLONK_FR_BYTES];

    /* Selector commitments ∈ G1 (affine, big-endian Fp coords) */
    uint8_t  Qm[ZKN_PLONK_G1_BYTES];
    uint8_t  Ql[ZKN_PLONK_G1_BYTES];
    uint8_t  Qr[ZKN_PLONK_G1_BYTES];
    uint8_t  Qo[ZKN_PLONK_G1_BYTES];
    uint8_t  Qc[ZKN_PLONK_G1_BYTES];

    /* Permutation commitments ∈ G1 */
    uint8_t  S1[ZKN_PLONK_G1_BYTES];
    uint8_t  S2[ZKN_PLONK_G1_BYTES];
    uint8_t  S3[ZKN_PLONK_G1_BYTES];

    /* SRS second point [τ]₂ ∈ G2 */
    uint8_t  X2[ZKN_PLONK_G2_BYTES];

} zkn_plonk_vk_t;

/* ── Proof ────────────────────────────────────────────────────────────── */

typedef struct {
    /* Wire commitments ∈ G1 */
    uint8_t  A[ZKN_PLONK_G1_BYTES];
    uint8_t  B[ZKN_PLONK_G1_BYTES];
    uint8_t  C[ZKN_PLONK_G1_BYTES];

    /* Grand product commitment ∈ G1 */
    uint8_t  Z[ZKN_PLONK_G1_BYTES];

    /* Quotient polynomial split commitments ∈ G1 */
    uint8_t  T1[ZKN_PLONK_G1_BYTES];
    uint8_t  T2[ZKN_PLONK_G1_BYTES];
    uint8_t  T3[ZKN_PLONK_G1_BYTES];

    /* Opening proofs ∈ G1 */
    uint8_t  Wxi[ZKN_PLONK_G1_BYTES];
    uint8_t  Wxiw[ZKN_PLONK_G1_BYTES];

    /* Evaluations ∈ Fr (big-endian 32 bytes) */
    uint8_t  eval_a[ZKN_PLONK_FR_BYTES];
    uint8_t  eval_b[ZKN_PLONK_FR_BYTES];
    uint8_t  eval_c[ZKN_PLONK_FR_BYTES];
    uint8_t  eval_s1[ZKN_PLONK_FR_BYTES];
    uint8_t  eval_s2[ZKN_PLONK_FR_BYTES];
    uint8_t  eval_zw[ZKN_PLONK_FR_BYTES];

} zkn_plonk_proof_t;

/* ── API ──────────────────────────────────────────────────────────────── */

/**
 * Verify a PLONK proof.
 *
 * All G1 coordinates are big-endian, non-Montgomery affine (x || y).
 * G2 coordinates are big-endian (x0 || x1 || y0 || y1).
 * Fr scalars are big-endian 32-byte.
 *
 * @param vk         Verification key
 * @param proof      Proof to verify
 * @param pub        Public inputs as big-endian Fr scalars
 * @param n_pub      Number of public inputs (must match vk->n_public)
 * @param ctx        BLS12-381 Montgomery context
 *
 * @return 1  if the proof is valid
 *         0  if the proof is invalid
 *        -1  on error
 */
int zkn_plonk_verify(const zkn_plonk_vk_t    *vk,
                     const zkn_plonk_proof_t  *proof,
                     const uint8_t            (*pub)[ZKN_PLONK_FR_BYTES],
                     int                        n_pub,
                     const zkn_mont_ctx384_t   *ctx);

#ifdef __cplusplus
}
#endif

#endif /* ZKN_PLONK_H */
