/*
 * test_fp4_384.c — Algebraic property tests for Fp4 = Fp2[y]/(y²−ξ) / BLS12-381
 *
 * Tests:
 *   1.  add_associativity       (a+b)+c == a+(b+c)
 *   2.  add_commutativity       a+b == b+a
 *   3.  add_identity            a+0 == a
 *   4.  add_inverse             a-a == 0
 *   5.  mul_associativity       (a·b)·c == a·(b·c)
 *   6.  mul_commutativity       a·b == b·a
 *   7.  mul_identity            a·1 == a
 *   8.  distributivity          a·(b+c) == a·b + a·c
 *   9.  sqr_vs_mul (a)          sqr(a) == mul(a,a)
 *   10. sqr_vs_mul (b)          sqr(b) == mul(b,b)
 *   11. sqr_vs_mul (c)          sqr(c) == mul(c,c)
 *   12. sqr_vs_mul (a+b)        sqr(a+b) == mul(a+b,a+b)
 *   13. sqr(0) == 0
 *   14. sqr(1) == 1
 *   15. norm_as_conj_mul        a·conj4(a) == norm(a)
 *   16. norm_c1_is_zero         norm(a).c1 == 0
 *   17. y_squared_eq_xi         y² == ξ in Fp4  (Frobenius / definition check)
 *
 * Copyright (c) 2025 ZKNOX / Kohaku
 */

#ifdef ZKN_HOST_TESTS

#include "zkn_fp4_384.h"
#include <stdio.h>
#include <string.h>

/* ── Test harness ───────────────────────────────────────────────────── */

static int g_tests  = 0;
static int g_passed = 0;
static int g_failed = 0;

#define TEST(name, cond) do {                                \
    g_tests++;                                               \
    if (cond) { g_passed++; printf("  PASS  %s\n", name); } \
    else       { g_failed++; printf("  FAIL  %s\n", name); } \
} while(0)

/* ── Helpers ────────────────────────────────────────────────────────── */

static int fp4_eq(const zkn_fp4_384_t *a, const zkn_fp4_384_t *b)
{
    return zkn_fp2_384_eq(&a->c0, &b->c0) &
           zkn_fp2_384_eq(&a->c1, &b->c1);
}

static int fp4_is_zero(const zkn_fp4_384_t *a)
{
    zkn_fp4_384_t z;
    zkn_fp4_384_zero(&z);
    return fp4_eq(a, &z);
}

/* Build an Fp2 from two small uint32 values. */
static void fp2_small(zkn_fp2_384_t *r, uint32_t re, uint32_t im,
                      const zkn_mont_ctx384_t *ctx)
{
    zkn_fe384_t n_re = {re};
    zkn_fe384_t n_im = {im};
    zkn_to_mont_384(r->c0, n_re, ctx);
    zkn_to_mont_384(r->c1, n_im, ctx);
}

/* Build an Fp4 from four small uint32 values. */
static void fp4_small(zkn_fp4_384_t *r,
                      uint32_t c0_re, uint32_t c0_im,
                      uint32_t c1_re, uint32_t c1_im,
                      const zkn_mont_ctx384_t *ctx)
{
    fp2_small(&r->c0, c0_re, c0_im, ctx);
    fp2_small(&r->c1, c1_re, c1_im, ctx);
}

static void fp4_one(zkn_fp4_384_t *r, const zkn_mont_ctx384_t *ctx)
{
    zkn_fp2_384_one(&r->c0, ctx);
    zkn_fp2_384_zero(&r->c1);
}

/* Fp4 conjugate: (c0, c1) → (c0, −c1) */
static void fp4_conj(zkn_fp4_384_t *r, const zkn_fp4_384_t *a,
                     const zkn_mont_ctx384_t *ctx)
{
    zkn_fp2_384_copy(&r->c0, &a->c0);
    zkn_fp2_384_neg(&r->c1, &a->c1, ctx);
}

/* Norm of a ∈ Fp4:  N(a) = c0² − ξ·c1²  ∈ Fp2 ⊂ Fp4 */
static void fp4_norm(zkn_fp4_384_t *r, const zkn_fp4_384_t *a,
                     const zkn_mont_ctx384_t *ctx)
{
    zkn_fp2_384_t t0, t1, xi_t1;
    zkn_fp2_384_sqr(&t0, &a->c0, ctx);
    zkn_fp2_384_sqr(&t1, &a->c1, ctx);
    zkn_fp2_384_mul_by_xi(&xi_t1, &t1, ctx);
    zkn_fp2_384_sub(&r->c0, &t0, &xi_t1, ctx);
    zkn_fp2_384_zero(&r->c1);
}

/* ── PRNG helpers (xorshift32, same pattern as test_fp2_384.c) ─────── */

static uint32_t fp4_xorshift32(uint32_t *state)
{
    uint32_t x = *state;
    x ^= x << 13;
    x ^= x >> 17;
    x ^= x << 5;
    *state = x;
    return x;
}

static void fp4_random_fe(zkn_fe384_t r, uint32_t *seed,
                          const zkn_fe384_t p)
{
    for (int i = 0; i < ZKN_MONT384_NLIMBS; i++)
        r[i] = fp4_xorshift32(seed);
    /* Reduce mod p (up to 10 conditional subtractions) */
    for (int k = 0; k < 10; k++) {
        zkn_limb_t borrow = 0;
        zkn_fe384_t tmp;
        for (int i = 0; i < ZKN_MONT384_NLIMBS; i++) {
            uint64_t d = (uint64_t)r[i] - p[i] - borrow;
            tmp[i] = (uint32_t)d;
            borrow = (uint32_t)(d >> 63);
        }
        if (!borrow) memcpy(r, tmp, sizeof(zkn_fe384_t));
    }
}

static void fp4_random_fp2(zkn_fp2_384_t *r, uint32_t *seed,
                            const zkn_mont_ctx384_t *ctx)
{
    zkn_fe384_t n0, n1;
    fp4_random_fe(n0, seed, ctx->p);
    fp4_random_fe(n1, seed, ctx->p);
    zkn_to_mont_384(r->c0, n0, ctx);
    zkn_to_mont_384(r->c1, n1, ctx);
}

static void fp4_random(zkn_fp4_384_t *r, uint32_t *seed,
                       const zkn_mont_ctx384_t *ctx)
{
    fp4_random_fp2(&r->c0, seed, ctx);
    fp4_random_fp2(&r->c1, seed, ctx);
}

/* ─────────────────────────────────────────────────────────────────────
 *  NEW: Random property tests with full 384-bit field elements
 *  (100 iterations, elements generated by xorshift32 PRNG)
 * ───────────────────────────────────────────────────────────────────── */

static void test_fp4_random(const zkn_mont_ctx384_t *ctx)
{
    printf("\n── Random property tests (100 × full-size Fp4 elements) ──\n");

    uint32_t seed = 0xC0FFEE42u;
    const int N = 100;

    int pass_add_comm  = 0, pass_add_assoc = 0;
    int pass_mul_comm  = 0, pass_mul_assoc = 0;
    int pass_dist      = 0;
    int pass_sqr_mul   = 0;
    int pass_norm_conj = 0;
    int pass_norm_c1z  = 0;

    for (int i = 0; i < N; i++) {
        zkn_fp4_384_t a, b, c;
        fp4_random(&a, &seed, ctx);
        fp4_random(&b, &seed, ctx);
        fp4_random(&c, &seed, ctx);

        /* 1. add commutativity: a+b == b+a */
        {
            zkn_fp4_384_t ab, ba;
            zkn_fp4_384_add(&ab, &a, &b, ctx);
            zkn_fp4_384_add(&ba, &b, &a, ctx);
            if (fp4_eq(&ab, &ba)) pass_add_comm++;
        }

        /* 2. add associativity: (a+b)+c == a+(b+c) */
        {
            zkn_fp4_384_t ab, ab_c, bc, a_bc;
            zkn_fp4_384_add(&ab, &a, &b, ctx);
            zkn_fp4_384_add(&ab_c, &ab, &c, ctx);
            zkn_fp4_384_add(&bc, &b, &c, ctx);
            zkn_fp4_384_add(&a_bc, &a, &bc, ctx);
            if (fp4_eq(&ab_c, &a_bc)) pass_add_assoc++;
        }

        /* 3. mul commutativity: a·b == b·a */
        {
            zkn_fp4_384_t ab, ba;
            zkn_fp4_384_mul(&ab, &a, &b, ctx);
            zkn_fp4_384_mul(&ba, &b, &a, ctx);
            if (fp4_eq(&ab, &ba)) pass_mul_comm++;
        }

        /* 4. mul associativity: (a·b)·c == a·(b·c) */
        {
            zkn_fp4_384_t ab, ab_c, bc, a_bc;
            zkn_fp4_384_mul(&ab, &a, &b, ctx);
            zkn_fp4_384_mul(&ab_c, &ab, &c, ctx);
            zkn_fp4_384_mul(&bc, &b, &c, ctx);
            zkn_fp4_384_mul(&a_bc, &a, &bc, ctx);
            if (fp4_eq(&ab_c, &a_bc)) pass_mul_assoc++;
        }

        /* 5. distributivity: a·(b+c) == a·b + a·c */
        {
            zkn_fp4_384_t bc, lhs, ab, ac, rhs;
            zkn_fp4_384_add(&bc, &b, &c, ctx);
            zkn_fp4_384_mul(&lhs, &a, &bc, ctx);
            zkn_fp4_384_mul(&ab, &a, &b, ctx);
            zkn_fp4_384_mul(&ac, &a, &c, ctx);
            zkn_fp4_384_add(&rhs, &ab, &ac, ctx);
            if (fp4_eq(&lhs, &rhs)) pass_dist++;
        }

        /* 6. sqr(a) == mul(a,a) */
        {
            zkn_fp4_384_t sq, mm;
            zkn_fp4_384_sqr(&sq, &a, ctx);
            zkn_fp4_384_mul(&mm, &a, &a, ctx);
            if (fp4_eq(&sq, &mm)) pass_sqr_mul++;
        }

        /* 7. norm_as_conj_mul: a · conj4(a) == norm(a) */
        {
            zkn_fp4_384_t conj_a, prod, norm_a;
            fp4_conj(&conj_a, &a, ctx);
            zkn_fp4_384_mul(&prod, &a, &conj_a, ctx);
            fp4_norm(&norm_a, &a, ctx);
            if (fp4_eq(&prod, &norm_a)) pass_norm_conj++;
        }

        /* 8. norm(a).c1 == 0 */
        {
            zkn_fp4_384_t norm_a;
            fp4_norm(&norm_a, &a, ctx);
            zkn_fp2_384_t zero_fp2;
            zkn_fp2_384_zero(&zero_fp2);
            if (zkn_fp2_384_eq(&norm_a.c1, &zero_fp2)) pass_norm_c1z++;
        }
    }

    char buf[90];
#define CHK(label, pass) do { \
    snprintf(buf, sizeof(buf), "rnd: " label " %d/%d", (pass), N); \
    g_tests++; \
    if ((pass) == N) { g_passed++; printf("  PASS  %s\n", buf); } \
    else             { g_failed++; printf("  FAIL  %s\n", buf); } \
} while(0)

    CHK("add commutativity",  pass_add_comm);
    CHK("add associativity",  pass_add_assoc);
    CHK("mul commutativity",  pass_mul_comm);
    CHK("mul associativity",  pass_mul_assoc);
    CHK("distributivity",     pass_dist);
    CHK("sqr == mul(a,a)",    pass_sqr_mul);
    CHK("norm_as_conj_mul",   pass_norm_conj);
    CHK("norm.c1 == 0",       pass_norm_c1z);
#undef CHK
}

/* ── Main ───────────────────────────────────────────────────────────── */

int main(void)
{
    printf("════════════════════════════════════════════\n");
    printf(" Fp4 = Fp2[y]/(y2-xi)  BLS12-381  tests\n");
    printf("════════════════════════════════════════════\n\n");

    const zkn_mont_ctx384_t *ctx = zkn_bls12381_ctx();

    /* --- Build test elements from small integers --- */
    zkn_fp4_384_t a, b, c, zero, one;

    /* a = (2 + 3·u) + (5 + 7·u)·y */
    fp4_small(&a,  2,  3,  5,  7, ctx);
    /* b = (11 + 13·u) + (17 + 19·u)·y */
    fp4_small(&b, 11, 13, 17, 19, ctx);
    /* c = (23 + 29·u) + (31 + 37·u)·y */
    fp4_small(&c, 23, 29, 31, 37, ctx);

    zkn_fp4_384_zero(&zero);
    fp4_one(&one, ctx);

    zkn_fp4_384_t t1, t2, t3, t4;

    printf("── Additive laws ──\n");

    /* (a+b)+c == a+(b+c) */
    zkn_fp4_384_add(&t1, &a, &b, ctx);
    zkn_fp4_384_add(&t1, &t1, &c, ctx);
    zkn_fp4_384_add(&t2, &b, &c, ctx);
    zkn_fp4_384_add(&t2, &a, &t2, ctx);
    TEST("add_associativity", fp4_eq(&t1, &t2));

    /* a+b == b+a */
    zkn_fp4_384_add(&t1, &a, &b, ctx);
    zkn_fp4_384_add(&t2, &b, &a, ctx);
    TEST("add_commutativity", fp4_eq(&t1, &t2));

    /* a+0 == a */
    zkn_fp4_384_add(&t1, &a, &zero, ctx);
    TEST("add_identity", fp4_eq(&t1, &a));

    /* a - a == 0 */
    zkn_fp4_384_sub(&t1, &a, &a, ctx);
    TEST("add_inverse (a-a=0)", fp4_is_zero(&t1));

    printf("\n── Multiplicative laws ──\n");

    /* (a·b)·c == a·(b·c) */
    zkn_fp4_384_mul(&t1, &a, &b, ctx);
    zkn_fp4_384_mul(&t1, &t1, &c, ctx);
    zkn_fp4_384_mul(&t2, &b, &c, ctx);
    zkn_fp4_384_mul(&t2, &a, &t2, ctx);
    TEST("mul_associativity", fp4_eq(&t1, &t2));

    /* a·b == b·a */
    zkn_fp4_384_mul(&t1, &a, &b, ctx);
    zkn_fp4_384_mul(&t2, &b, &a, ctx);
    TEST("mul_commutativity", fp4_eq(&t1, &t2));

    /* a·1 == a */
    zkn_fp4_384_mul(&t1, &a, &one, ctx);
    TEST("mul_identity", fp4_eq(&t1, &a));

    /* a·(b+c) == a·b + a·c */
    zkn_fp4_384_add(&t3, &b, &c, ctx);
    zkn_fp4_384_mul(&t1, &a, &t3, ctx);
    zkn_fp4_384_mul(&t2, &a, &b, ctx);
    zkn_fp4_384_mul(&t3, &a, &c, ctx);
    zkn_fp4_384_add(&t4, &t2, &t3, ctx);
    TEST("distributivity", fp4_eq(&t1, &t4));

    printf("\n── Squaring ──\n");

    zkn_fp4_384_sqr(&t1, &a, ctx);
    zkn_fp4_384_mul(&t2, &a, &a, ctx);
    TEST("sqr_vs_mul (a)", fp4_eq(&t1, &t2));

    zkn_fp4_384_sqr(&t1, &b, ctx);
    zkn_fp4_384_mul(&t2, &b, &b, ctx);
    TEST("sqr_vs_mul (b)", fp4_eq(&t1, &t2));

    zkn_fp4_384_sqr(&t1, &c, ctx);
    zkn_fp4_384_mul(&t2, &c, &c, ctx);
    TEST("sqr_vs_mul (c)", fp4_eq(&t1, &t2));

    zkn_fp4_384_add(&t3, &a, &b, ctx);
    zkn_fp4_384_sqr(&t1, &t3, ctx);
    zkn_fp4_384_mul(&t2, &t3, &t3, ctx);
    TEST("sqr_vs_mul (a+b)", fp4_eq(&t1, &t2));

    zkn_fp4_384_sqr(&t1, &zero, ctx);
    TEST("sqr(0)==0", fp4_is_zero(&t1));

    zkn_fp4_384_sqr(&t1, &one, ctx);
    TEST("sqr(1)==1", fp4_eq(&t1, &one));

    printf("\n── Norm / conjugate ──\n");

    {
        zkn_fp4_384_t conj_a, prod, norm_a;
        fp4_conj(&conj_a, &a, ctx);
        zkn_fp4_384_mul(&prod, &a, &conj_a, ctx);
        fp4_norm(&norm_a, &a, ctx);
        TEST("norm_as_conj_mul", fp4_eq(&prod, &norm_a));

        zkn_fp2_384_t zero_fp2;
        zkn_fp2_384_zero(&zero_fp2);
        TEST("norm_c1_is_zero", zkn_fp2_384_eq(&norm_a.c1, &zero_fp2));
    }

    printf("\n── Frobenius: y^2 == xi = (1+u) ──\n");

    /*
     * y_elem = 0 + 1·y  →  c0=(0,0), c1=(1,0) in Fp2
     * sqr(y_elem) must equal c0=xi=(1,1), c1=0
     * because y² = ξ is the defining relation of Fp4.
     */
    {
        zkn_fp4_384_t y_elem;
        zkn_fp2_384_zero(&y_elem.c0);
        zkn_fp2_384_one(&y_elem.c1, ctx);

        zkn_fp4_384_t y_sqr;
        zkn_fp4_384_sqr(&y_sqr, &y_elem, ctx);

        /* Expected: c0 = xi = 1+u = (1,1), c1 = 0 */
        zkn_fp4_384_t xi_elem;
        fp2_small(&xi_elem.c0, 1, 1, ctx);
        zkn_fp2_384_zero(&xi_elem.c1);

        TEST("y_squared_eq_xi", fp4_eq(&y_sqr, &xi_elem));
    }

    /* ── NEW: random tests with large Fp elements ── */
    test_fp4_random(ctx);

    /* ── Summary ── */
    printf("\n════════════════════════════════════════════\n");
    if (g_failed == 0)
        printf(" All %d tests passed\n", g_passed);
    else
        printf(" %d/%d tests FAILED\n", g_failed, g_tests);
    printf("════════════════════════════════════════════\n");

    return g_failed ? 1 : 0;
}

#endif /* ZKN_HOST_TESTS */
