/*
 * test_bech32m_host.c — Tests for zkn_bech32m (RAILGUN 0zk addresses)
 *
 * Reference vector generated by js/gen_0zk_vector.mjs (using @scure/base).
 *
 * Copyright (c) 2025 ZKNOX
 */

#ifdef ZKN_HOST_TESTS

#include <stdio.h>
#include <string.h>
#include "zkn_bech32m.h"

static int test_count = 0;
static int fail_count = 0;

static void check_ok(const char *name, int rc)
{
    test_count++;
    if (rc == 0)
        printf("[PASS] %s\n", name);
    else {
        printf("[FAIL] %s (rc=%d)\n", name, rc);
        fail_count++;
    }
}

static void check_bool(const char *name, int cond)
{
    test_count++;
    if (cond)
        printf("[PASS] %s\n", name);
    else {
        printf("[FAIL] %s\n", name);
        fail_count++;
    }
}

static void check_bytes(const char *name,
                        const uint8_t *got, const uint8_t *expected, size_t len)
{
    test_count++;
    if (memcmp(got, expected, len) == 0) {
        printf("[PASS] %s\n", name);
    } else {
        printf("[FAIL] %s\n", name);
        printf("    expected = 0x");
        for (size_t i = 0; i < len; i++) printf("%02x", expected[i]);
        printf("\n    got      = 0x");
        for (size_t i = 0; i < len; i++) printf("%02x", got[i]);
        printf("\n");
        fail_count++;
    }
}

/* Reference vector from js/gen_0zk_vector.mjs */
static const char ADDR[] =
    "0zk1qyqqzqsrqszsvpcgpy9qkrqdpc83qygjzv2p29shrqv35xcur50pl242424242424"
    "tqvrskrcnzud37ge89vhnxdem8ap5wj602dt4khmrva4k7umh0d7srx2fs";

static const uint8_t EXPECTED_PAYLOAD[73] = {
    0x01,
    /* mpk: 0..31 */
    0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07,
    0x08, 0x09, 0x0a, 0x0b, 0x0c, 0x0d, 0x0e, 0x0f,
    0x10, 0x11, 0x12, 0x13, 0x14, 0x15, 0x16, 0x17,
    0x18, 0x19, 0x1a, 0x1b, 0x1c, 0x1d, 0x1e, 0x1f,
    /* networkXOR: 0xaa × 8 */
    0xaa, 0xaa, 0xaa, 0xaa, 0xaa, 0xaa, 0xaa, 0xaa,
    /* vpub: 0xc0..0xdf */
    0xc0, 0xc1, 0xc2, 0xc3, 0xc4, 0xc5, 0xc6, 0xc7,
    0xc8, 0xc9, 0xca, 0xcb, 0xcc, 0xcd, 0xce, 0xcf,
    0xd0, 0xd1, 0xd2, 0xd3, 0xd4, 0xd5, 0xd6, 0xd7,
    0xd8, 0xd9, 0xda, 0xdb, 0xdc, 0xdd, 0xde, 0xdf,
};

static void test_decode_mpk(void)
{
    printf("\n--- zkn_0zk_decode_mpk ---\n");

    uint8_t mpk[32];
    check_ok("decode mpk", zkn_0zk_decode_mpk((const uint8_t *)ADDR, 127, mpk));
    check_bytes("mpk matches", mpk, EXPECTED_PAYLOAD + ZKN_0ZK_MPK_OFFSET, 32);
}

static void test_decode_full(void)
{
    printf("\n--- zkn_0zk_decode (full payload) ---\n");

    uint8_t payload[ZKN_0ZK_DECODED_LEN];
    size_t out_len = 0;
    check_ok("decode full", zkn_0zk_decode((const uint8_t *)ADDR, 127, payload, &out_len));
    check_bool("decoded length = 73", out_len == ZKN_0ZK_DECODED_LEN);
    check_bytes("payload matches", payload, EXPECTED_PAYLOAD, ZKN_0ZK_DECODED_LEN);
}

static void test_rejections(void)
{
    printf("\n--- input rejection ---\n");

    uint8_t mpk[32];

    /* Wrong length */
    check_bool("reject wrong length (126)",
               zkn_0zk_decode_mpk((const uint8_t *)ADDR, 126, mpk) != 0);
    check_bool("reject wrong length (128)",
               zkn_0zk_decode_mpk((const uint8_t *)ADDR, 128, mpk) != 0);

    /* Wrong HRP */
    char bad_hrp[128];
    memcpy(bad_hrp, ADDR, 127);
    bad_hrp[0] = '1';  /* "1zk1..." instead of "0zk1..." */
    check_bool("reject wrong HRP",
               zkn_0zk_decode_mpk((const uint8_t *)bad_hrp, 127, mpk) != 0);

    /* Corrupted checksum (flip a char inside the data part) */
    char bad_chk[128];
    memcpy(bad_chk, ADDR, 127);
    bad_chk[126] = (bad_chk[126] == 's') ? 'q' : 's';  /* flip last char */
    check_bool("reject bad checksum",
               zkn_0zk_decode_mpk((const uint8_t *)bad_chk, 127, mpk) != 0);

    /* Invalid charset char ('b' is not in bech32 alphabet) */
    char bad_charset[128];
    memcpy(bad_charset, ADDR, 127);
    bad_charset[10] = 'b';
    check_bool("reject invalid charset",
               zkn_0zk_decode_mpk((const uint8_t *)bad_charset, 127, mpk) != 0);

    /* Non-ASCII byte */
    char non_ascii[128];
    memcpy(non_ascii, ADDR, 127);
    non_ascii[20] = (char)0xff;
    check_bool("reject non-ASCII byte",
               zkn_0zk_decode_mpk((const uint8_t *)non_ascii, 127, mpk) != 0);
}

int main(void)
{
    printf("=== zkn_bech32m test suite ===\n");

    test_decode_mpk();
    test_decode_full();
    test_rejections();

    printf("\n=== Results: %d/%d passed ===\n",
           test_count - fail_count, test_count);

    return fail_count ? 1 : 0;
}

#endif /* ZKN_HOST_TESTS */
